[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:ssh]
command=/usr/sbin/sshd -D
autorestart=true
stdout_logfile=/var/log/supervisor_ssh.log
stderr_logfile=/var/log/supervisor_ssh_err.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
stdout_logfile=/var/log/supervisor_nginx.log
stderr_logfile=/var/log/supervisor_nginx_err.log

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd.conf
autorestart=true
stdout_logfile=/var/log/supervisor_vsftpd.log
stderr_logfile=/var/log/supervisor_vsftpd_err.log

[program:smbd]
command=/usr/sbin/smbd -F --no-process-group
autorestart=true
stdout_logfile=/var/log/supervisor_smbd.log
stderr_logfile=/var/log/supervisor_smbd_err.log

[program:mysql]
command=/usr/sbin/mysqld --user=mysql
autorestart=true
stdout_logfile=/var/log/supervisor_mysql.log
stderr_logfile=/var/log/supervisor_mysql_err.log

[program:postfix]
command=/usr/sbin/postfix start-fg
autorestart=true
stdout_logfile=/var/log/supervisor_postfix.log
stderr_logfile=/var/log/supervisor_postfix_err.log

[program:mountd]
command=/usr/sbin/rpc.mountd -F
autorestart=true
stdout_logfile=/var/log/supervisor_mountd.log
stderr_logfile=/var/log/supervisor_mountd_err.log

[program:php-fpm]
command=/usr/sbin/php-fpm8.1 -F
autorestart=true
stdout_logfile=/var/log/supervisor_php_fpm.log
stderr_logfile=/var/log/supervisor_php_fpm_err.log
